import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'

const font = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Distrum | The Next Platform',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
