import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { cn } from '@/lib/utils'

const font = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Distrum | The Next Platform',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(
            font.className,
            'bg-white dark:bg-[#313338]'
          )
        }>
          <ThemeProvider
            attribute='class'
            defaultTheme='dark'
            enableSystem
            storageKey='distrum'
          >
          {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
